export const GET_POKEMON = 'GET_POKEMON';
export const POKEMON_MULTIPLE_LOADING = 'POKEMON_MULTIPLE_LOADING';
export const POKEMON_LIST_LOADING = 'POKEMON_LIST_LOADING';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL';
export const POKEMON_MULTIPLE_SUCCESS = 'POKEMON_MULTIPLE_SUCCESS';
export const POKEMON_MULTIPLE_FAIL = 'POKEMON_MULTIPLE_FAIL';